name: untitled
description: A description for your project
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add any other dependencies you need for your project

flutter:
  assets:
    - assets/images/   # Add the assets folder path where your images are located
